import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../conponements/header/header";
import Footer from "@/conponements/footer/footer";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full gap-10 flex flex-col items-center font-sans max-w-360 m-auto md:pt-10 md:px-36 ">
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
